plugins {
    id 'application'
}

repositories {
    def stagingRepositoryRoot = providers.gradleProperty('stagingRepositoryRoot').get()
    [
        'myservicebus-abstractions',
        'myservicebus-di',
        'myservicebus-logging',
        'myservicebus-tasks',
        'myservicebus',
        'myservicebus-processor',
        'myservicebus-serialization-bson',
        'myservicebus-postgresql',
        'myservicebus-inspection',
        'myservicebus-monitoring',
        'myservicebus-rabbitmq',
        'myservicebus-azure-service-bus',
        'myservicebus-amazon-sqs',
        'myservicebus-testing'
    ].each { module ->
        maven {
            url = uri("${stagingRepositoryRoot}/${module}/build/repository")
        }
    }
    mavenCentral()
}

dependencies {
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-abstractions:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-di:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-logging:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-tasks:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus:0.1.0-preview.7'
    annotationProcessor 'io.github.marinasundstrom.myservicebus:myservicebus-processor:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-serialization-bson:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-postgresql:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-inspection:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-monitoring:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-rabbitmq:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-azure-service-bus:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-amazon-sqs:0.1.0-preview.7'
    implementation 'io.github.marinasundstrom.myservicebus:myservicebus-testing:0.1.0-preview.7'
}

application {
    mainClass = 'com.myservicebus.packagesmoke.PackageSmoke'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
