<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/MyServiceBus/MyServiceBus.csproj"
                      AdditionalProperties="EnableNet11RuntimeAsyncTarget=true" />
  </ItemGroup>

</Project>
