@TestApp_HostAddress = https://localhost:7244

GET {{TestApp_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TestApp_HostAddress}}/publish

###

GET {{TestApp_HostAddress}}/publish/fault

###

GET {{TestApp_HostAddress}}/send

###

GET {{TestApp_HostAddress}}/send/fault

###

POST {{TestApp_HostAddress}}/schedule?delaySeconds=120

###

DELETE {{TestApp_HostAddress}}/schedule/00000000-0000-0000-0000-000000000000

###

GET {{TestApp_HostAddress}}/request

###

GET {{TestApp_HostAddress}}/request/fault

###

GET {{TestApp_HostAddress}}/request_multi

###

GET {{TestApp_HostAddress}}/request_multi/fault

###
